# Site settings

title: Volim Kafu, a ti? 
tagline: Pridruži se ;)
email: volimkafu@outlook.com  
copyright: Volim Kafu
keywords: volimo, kafu, volim, kafici, kofetin

description: > # this means to ignore newlines until "url:". One indent required.
  Volimo kafu, svaki dan uživamo u jednoj šolji (ili više) i uvek istražujemo nove ukuse... Da li si i ti jedan od nas?

# the base hostname & protocol for your site
url: "http://volimkafu.club"

twitter_username: javolimkafu
github_username:  volimkafu

default_image: /img/blog/volim-kafu.png

# Pre-processing

markdown: kramdown
highlighter: pygments
safe: true
permalink: pretty # YYYY/MM/DD/page-title/index.html
lsi: true # Lexical analysis (true) takes longer for higher quality
# sass:
#  style: :compressed

# Exclude from Jekyll processing

exclude: ["vendor", "README.md", "node_modules", "gulpfile.js", "package.json"]

# Lists

tag_items: 10     # Applies to categories and tags lists
recent_items: 4 # Applies to recent posts, apps lists
related_items: 4  # Applies to related posts and apps lists

# Layout

pagebar: true # Show (true) page sidebar menu or hide (false) 
postbar: true # Show (true) post sidebar or hide (false) 

# Features

reading_time: true    # Show est. reading time for posts
facebook: true        # Use facebook features
comments: facebook      # Switch disqus | facebook | none - comments. facebook = true required for facebook comments

# Embeds

# disqus_name: volimkafu            # Your site name at Disqus

youtube_controls: 0               # Turn on=1/off=0 Youtube player features when embedding videos

google_map_zoom: 16               # 1=Global zoom 18=Street Level
google_map_view: satellite        # hybrid | satellite | roadmap
google_map_height: 450            # Default map height. Width adjusts to container.

# API Keys. PLEASE DO NOT USE THESE KEYS. Get your own at links in comments.

google_api_key: "AIzaSyDmt_iRsE8kQ1glUPC2GZpNLBsw1Laj9_0" # https://code.google.com/apis/console/
google_analytics_ua: "UA-60258140-1" # Google Analytics site specific id
google_cse_id: "014506222527227995562:1nur7kuw8x8" # Google Custom Search Engine unique id

mapbox: "pk.eyJ1Ijoidm9saW1rYWZ1IiwiYSI6Im1laWRMU1UifQ.jxHRW1L0yZI1rk-ec9hXXA"

facebook_app: "892030024171405" # https://developers.facebook.com/

mailchimp_u: "62a03f69deb1da9096a11045a" # Mailchimp u=unique identification
mailchimp_id: "7332929351" # Mailchip id

addthis_pubid: "ra-54f3cb5c0a7ccafe" # Get your pubid at https://www.addthis.com/dashboard

